name: Daily Commit

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 03:30 UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy change - 23f1000242@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > daily-run.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-run.txt
          git commit -m "Daily commit at $(date)"
          git push
